[phases.setup]
nixPkgs = ["jdk17"]

[phases.install]
cmds = ["mvn dependency:resolve -q"]

[phases.build]
cmds = ["mvn clean package -DskipTests -q"]

[start]
cmd = "java -jar target/taskflow-backend-1.0.0.jar"
